### ISSUE TITLE
How could I use this linter with golangci-lint?

### ISSUE THREAD

**Issue by piratf** [iwittkau/proto-golint#3]
I can't find this project by name in the golangci linter list: https://golangci-lint.run/usage/linters/.
But in the commit message, I found upgrade information about supports golangci-lint. 
Could you tell me how to use this linter? Thank you.

**Comment by iwittkau** [comment]
Hi!

There is a [make target](https://github.com/iwittkau/proto-golint/blob/master/Makefile#L11) to install the linter as a plugin, as this linter is not (yet) integrated in `golangci-lint`.

When you've installed the plugin you can add it to your `.golangci.yml`

```yml
linters-settings:
 custom:
   proto-golint:
     path: /Users/iwittkau/go/bin/proto-golint-plugin.so
     description: report direct access to proto message fields when getters can be used
     original-url: github.com/iwittkau/proto-golint
linters:
  enable:
    - proto-golint
```

… adapt it with the path to the plugin on your machine. The make target will put out the path where the plugin was copied to (`$GOPATH/bin/proto-golint-plugin.so`).

The reason why I need to update the dependencies regularly is due to the fact that this linter is compiled outside of `golangci-lint` and not imported by their code directly. The versions of the shared dependencies must exactly match those also imported by `golangci-lint`.
